//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAUTIZO
    {
        public int id_bautizo { get; set; }
        public int id_usuario_registro { get; set; }
        public string nombre_bautizado { get; set; }
        public string fecha_nacimiento_bautizado { get; set; }
        public string nombre_padre { get; set; }
        public string nombre_madre { get; set; }
        public string nombres_padrinos { get; set; }
        public string fecha_bautizo { get; set; }
    }
}
