//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONFIRMACION
    {
        public int id_confirmacion { get; set; }
        public int id_usuario_registro { get; set; }
        public string nombre_confirmando { get; set; }
        public System.DateTime fecha_nacimiento_confirmando { get; set; }
        public string nombre_madre_confirmando { get; set; }
        public string nombre_padre_confirmando { get; set; }
        public string nombre_padrinos { get; set; }
        public System.DateTime fecha_confirmacion { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
    }
}
