//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PARROQUIAEntities : DbContext
    {
        public PARROQUIAEntities()
            : base("name=PARROQUIAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BAUTIZO> BAUTIZOes { get; set; }
        public virtual DbSet<CONFIRMACION> CONFIRMACIONs { get; set; }
        public virtual DbSet<MATRIMONIO> MATRIMONIOs { get; set; }
        public virtual DbSet<ROL> ROLs { get; set; }
        public virtual DbSet<SOLICITUD> SOLICITUDs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<USUARIO> USUARIOs { get; set; }
    }
}
