//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATRIMONIO
    {
        public int id_matrimonio { get; set; }
        public int id_usuario_registro { get; set; }
        public string nombre_esposo { get; set; }
        public System.DateTime fecha_nacimiento_esposo { get; set; }
        public string profesion_esposo { get; set; }
        public string nombre_esposa { get; set; }
        public System.DateTime fecha_nacimiento_esposa { get; set; }
        public string presion_esposa { get; set; }
        public System.DateTime fecha_matrimonio { get; set; }
        public string nombre_padrinos { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
    }
}
