//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOLICITUD
    {
        public int id_solicitud { get; set; }
        public Nullable<int> id_usuario_seguimiento { get; set; }
        public string nombre_solicitante { get; set; }
        public string descripcion_solicitud { get; set; }
        public byte estado { get; set; }
    }
}
