CREATE DATABASE [SampleEntityFramework]

USE SampleEntityFramework


CREATE TABLE PET_TYPE(
	PET_TYPE_ID INT IDENTITY(1,1) NOT NULL,
	BREED VARCHAR(10),
	PRIMARY KEY(PET_TYPE_ID)
);


CREATE TABLE PET(
	PET_ID INT IDENTITY(1,1) NOT NULL,
	PET_NAME VARCHAR(10) NOT NULL,
	AGE INT NOT NULL,
	PET_TYPE_ID INT NOT NULL,
	PRIMARY KEY(PET_ID),
	FOREIGN KEY(PET_TYPE_ID ) REFERENCES PET_TYPE(PET_TYPE_ID)
)